name = "cpsa2lean"
version = "0.1.0"
defaultTargets = ["Cpsa2Lean", "cpsa"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[lean_lib]]
name = "Cpsa2Lean"

[[lean_exe]]
name = "cpsa"
root = "Main"
