name = "leancpsa"
version = "0.1.1"
defaultTargets = ["LeanCPSA", "leancpsa"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[lean_lib]]
name = "LeanCPSA"

[[lean_exe]]
name = "leancpsa"
root = "Main"
